spring:
  application:
    name: myclient

server:
  port: 9100
  
logging.level:
  org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
  org.springframework.cloud: DEBUG
  com.netflix.loadbalancer: DEBUG
  
spring.http.log-request-details: true